### ISSUE TITLE
Section 5.1

### ISSUE THREAD

**Issue by aboba** [emcho/trickle-ice#18]
5.1.  Sending the Initial Answer

   An agent can respond to an initial offer at any point while gathering
   candidates.  The answer can again contain any set of candidates,
   including all candidates or no candidates.  (The benefit of including
   no candidates is to send the answer as quickly as possible, so that
   both parties can consider the overall session to be under active
   negotiation as soon as possible.)  Unless the answering agent is
   protecting host addresses for privacy reasons, it would typically
   construct this initial answer including only host addresses, thus
   enabling the remote party to also start forming check lists and
   performing connectivity checks.

[BA] The lack of normative language is inconsistent with Section 4.
Also, don't understand why including only host addresses enables forming
of check lists whereas other candidates would not permit this. 

   In application protocols that use SDP, the answer MUST indicate
   support for Trickle ICE as described in Section 3.

[BA] Doesn't SDP guidance make more sense in the SIP draft?

**Comment by stpeter** [comment]
Addressed by https://github.com/ice-wg/trickle/commit/703bb3005264887155450202ee74be728ac771b9#diff-f7ced034e08b14404c7832d8f5f19567
