### ISSUE TITLE
Section 8.2:  "end of candidates" for media-stream versus session

### ISSUE THREAD

**Issue by aboba** [emcho/trickle-ice#21]
Once all candidate gathering is completed or expires for a specific
   media stream, the agent will generate an "end-of-candidates"
   indication for that stream and send it to the remote agent via the
   signaling channel....
   When an end-of-candidates indication is sent as part of an offer or
   an answer, it can be considered to apply to the session as a whole,
   which is equivalent to having it apply to all media streams.

[BA] These two paragraphs would seem to contradict each other.  One talks about 
"end of candidates" for a media stream and the other talks about it applying
to all media streams.  Should the latter material be moved to the SIP draft?

**Comment by stpeter** [comment]
This might be covered by https://github.com/ice-wg/trickle/commit/5893a7ef95eade0fc16d480258d99566feb3eee7#diff-f7ced034e08b14404c7832d8f5f19567R705 (or maybe that just moves the problem around). Leaving this issue open so that @emcho and I can discuss.

**Comment by stpeter** [comment]
Based on review of the text by @emcho I am closing this issue.
