### ISSUE TITLE
Peter Thatcher's Review

### ISSUE THREAD

**Issue by aboba** [emcho/trickle-ice#22]
---------- Forwarded message ----------
From: Peter Thatcher <pthatcher@google.com>
Date: Mon, Oct 31, 2016 at 7:30 AM
Subject: [Ice] Review of trickle ICE
To: ice@ietf.org

I reviewed the latest draft of ICE (in github) and have the following comments, many of them similar to Taylor's recent comments:

- There are lots of references to offers and answers.  5245bis no longer uses that terminology and I think trickle ICE should be updated to reflect the new terminology.

- Also, there are lots of references still to SDP that I think we can get rid of. 

- The handling of duplicate candidates seems to still be "first one wins", and we've decided to change that to "highest priority wins, except for peer-reflexive" or something like that.  Either way, the doc needs to be updated to match the decision.

- Why is session-level end-of-candidates restricted to offers/answers.   Better yet, if you don't talk about offers/answers at all, this should just go away.

- It says ICE "will conclude" after nomination, but it should probably say "may conclude".

- It seems like ICE restarts are basically re-defined.  But why do that?  Why not just say that ICE restarts work just like 5245bis, except that you can assume trickle ICE is supporte if it was previously?   Or, better yet, why not just leave that to signaling to decide?

- "ICE harvester" is strange term.  "Gatherer" might be a better one.

_______________________________________________
Ice mailing list
Ice@ietf.org
https://www.ietf.org/mailman/listinfo/ice

**Comment by stpeter** [comment]
Partially addressed by https://github.com/ice-wg/trickle/commit/ad3b33d2677f052a79d5e8bf3ce6034b2edafb80#diff-f7ced034e08b14404c7832d8f5f19567 (other aspects covered by previous checkins from @emcho, I think).
