### ISSUE TITLE
Add a section about how an ICE restart works without a full offer/answer

### ISSUE THREAD

**Issue by emcho** [emcho/trickle-ice#3]

**Comment by stpeter** [comment]
I think this is still open. Will try to formulate some text.

**Comment by stpeter** [comment]
@emcho Do you think we still need some text on this issue? I think you have a better understanding of what we might want to say here...

**Comment by stpeter** [comment]
@emcho I _think_ we might have addressed this one - you agree?

**Comment by stpeter** [comment]
Based on review of the text by @emcho I am closing this issue.
